In [123]:
!pip install praw
import praw
import pandas as pd
import datetime as dt
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

import re
from bs4 import BeautifulSoup

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [173]:
reddit = praw.Reddit(client_id='WK7Bb4kSnRez8g',
                     client_secret='NYWBOS04ouTSPO0cKhsMLqs-SWQ',
                     user_agent='Reddit_India_Data')
india_subreddit = reddit.subreddit('india')

In [174]:

flairs = ["AskIndia", "Non-Political", "[R]eddiquette", "Scheduled", "Photography", "Science/Technology", "Politics", "Business/Finance", "Policy/Economy", "Sports", "Food", "AMA"]
post_dict = []

In [175]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [176]:
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

def readableTime(created):
    return dt.datetime.utcfromtimestamp(created)


#To convert data elements into string objects
def toStr(item):
    return str(item)

_replace = re.compile('[/(){}\|@,;]')
badSymbols = re.compile('[^0-9a-z #+_]')
stopWords = set(stopwords.words('english'))

#To clean text within dataset

# sentences = 
corpus=[]
lemmatizer = WordNetLemmatizer()
def cleanText(string):
    string = BeautifulSoup(string, "lxml").string
    string = string.lower() 
    string = _replace.sub(' ', string)
    string = badSymbols.sub('', string)
    string=nltk.sent_tokenize(string)
    words = [lemmatizer.lemmatize(word) for word in string if word not in set(stopwords.words('english'))]
    string= ' '.join(words)  
#     string = ' '.join(word for word in string.split() if word not in stopWords)
    corpus.append(string)
    return string

In [185]:
for flair in flairs:
    submissions = india_subreddit.search(f"flair_name:{flair}",limit=20000)
    for submission in submissions:
        post_dict.append([submission.title,
                submission.id,
                submission.link_flair_text,
                submission.author,
                submission.url,
                submission.num_comments,
                submission.score,
                submission.created])
post_dict = pd.DataFrame(post_dict,columns=['title', 'id', 'flair', 'author', 'url', 'num_comments', 'score', 'created'])
topics = pd.DataFrame(post_dict)
#Sorting data based in ascending order of flair
topics.sort_values('flair', inplace=True)
#Changing Unix time to UTC time.
topics['timestamp'] = topics['created'].apply(readableTime)
del topics['created']
#Deleting any duplicate rows
topics.drop_duplicates(subset=None, inplace=True)
topics.to_csv('/content/drive/MyDrive/RedditFlairDetector-master/Jupyter Notebooks/Data.csv', index=False)

It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readt

In [188]:
df=pd.read_csv('/content/drive/MyDrive/RedditFlairDetector-master/Jupyter Notebooks/Data.csv')

In [189]:
df.shape

(3197, 8)

In [180]:
-df.head()

title  ...            timestamp
0  School student. Currently in 11th standard. De...  ...  2017-07-02 15:34:17
1          hi this is rajat kapoor- ask me anything!  ...  2015-07-10 12:35:36
2                        [NP] I am a dentist. AMA!!!  ...  2016-04-26 12:58:58
3  Hi Reddit, i'm Siddharth Agarwal & i'm current...  ...  2016-07-11 13:32:51
4  [AMA] Hi r/India! I'm a CA and would love to a...  ...  2017-02-11 05:43:55

[5 rows x 8 columns]

In [181]:
df.isnull().sum()

title           0
id              0
flair           0
author          0
url             0
num_comments    0
score           0
timestamp       0
dtype: int64

In [182]:
df.shape

(3197, 8)

In [183]:
df['flair'].shape

(3197,)

In [79]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
flair_encoded = le.fit_transform(df['flair'])

print(len(flair_encoded))
from sklearn.preprocessing import OneHotEncoder

flair_encoded = le.fit_transform(df['flair'])
flair_encoded = flair_encoded.reshape(len(flair_encoded), -1)
one = OneHotEncoder(sparse=False)

print(one.fit_transform(flair_encoded))

2824
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [136]:

Y = pd.get_dummies(df['flair']).values
# df['flair'] = one.fit_transform(flair_encoded)
# print(df)

In [137]:
df['flair']

0                 AMA
1                 AMA
2                 AMA
3                 AMA
4                 AMA
            ...      
2819    [R]eddiquette
2820    [R]eddiquette
2821    [R]eddiquette
2822    [R]eddiquette
2823    [R]eddiquette
Name: flair, Length: 2824, dtype: object

In [138]:
df.head()

title  ...            timestamp
0  School student. Currently in 11th standard. De...  ...  2017-07-02 15:34:17
1          hi this is rajat kapoor- ask me anything!  ...  2015-07-10 12:35:36
2                        [NP] I am a dentist. AMA!!!  ...  2016-04-26 12:58:58
3  Hi Reddit, i'm Siddharth Agarwal & i'm current...  ...  2016-07-11 13:32:51
4  [AMA] Hi r/India! I'm a CA and would love to a...  ...  2017-02-11 05:43:55

[5 rows x 8 columns]

In [139]:
import nltk
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [140]:
df['title'] =df['title'].apply(toStr)
df['title'] =df['title'].apply(cleanText)
feature_Grp = df['title'] + df['url']
df = df.assign(feature_Grp = feature_Grp)

In [141]:
df.shape

(2824, 9)

In [142]:
df.head()

title  ...                                        feature_Grp
0  school student currently in 11th standard debu...  ...  school student currently in 11th standard debu...
1            hi this is rajat kapoor ask me anything  ...  hi this is rajat kapoor ask me anythinghttps:/...
2                              np i am a dentist ama  ...  np i am a dentist amahttps://www.reddit.com/r/...
3  hi reddit  im siddharth agarwal  im currently ...  ...  hi reddit  im siddharth agarwal  im currently ...
4  ama hi r india im a ca and would love to answe...  ...  ama hi r india im a ca and would love to answe...

[5 rows x 9 columns]

In [143]:
corpus=[]
corpus = []
for i in range(0, len(df['title'])):
    corpus.append(df['title'][i])

In [144]:
corpus

['school student currently in 11th standard debunking all your myths about schooling',
 'hi this is rajat kapoor ask me anything',
 'np i am a dentist ama',
 'hi reddit  im siddharth agarwal  im currently on a walk  3000kms  along the river ganga from sea to source and i have already walked more than 500kms in one month ama',
 'ama hi r india im a ca and would love to answer questions you have about finance economy taxation  ask me anything',
 'hey reddit i am sandeep goenka  cofounder of zebpay india bitcoin exchange ask me anything',
 'this is cartoonist satish acharya ask me anything today',
 'hello r india  i am vijay shekhar sharma from paytm   one97 ask me anything',
 'i cook though not professionally   will be happy to answer any of your questions regarding cooking to the best of my knowledge  so ama',
 'hey  i am raghav mandava  one of the first professional comedians and comedy producers in india if you dont know me  thats okay  lets talk comedy',
 'we are vikramaditya motwane

In [145]:
len(corpus)

2824

In [146]:
df.to_csv('/content/drive/MyDrive/RedditFlairDetector-master/Jupyter Notebooks/Final_formatted_data.csv')


In [147]:
import matplotlib.pyplot as plt
from collections import Counter
import pandas as pd
import numpy as np
import seaborn as sns
#using inline to Graphs as Cell outputs.
%matplotlib inline
reddit_data = pd.read_csv('/content/drive/MyDrive/RedditFlairDetector-master/Jupyter Notebooks/Final_formatted_data.csv')
reddit_data.head(4)

Unnamed: 0  ...                                        feature_Grp
0           0  ...  school student currently in 11th standard debu...
1           1  ...  hi this is rajat kapoor ask me anythinghttps:/...
2           2  ...  np i am a dentist amahttps://www.reddit.com/r/...
3           3  ...  hi reddit  im siddharth agarwal  im currently ...

[4 rows x 10 columns]

In [148]:
reddit_data.shape

(2824, 10)

In [149]:
len(corpus)

2824

In [150]:
voc_size=5000

In [151]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[4069, 783, 2397, 4672, 124, 713, 2098, 1072, 3913, 926, 508, 1266],
 [646, 1278, 1679, 734, 3723, 2199, 40, 4511],
 [18, 2100, 2192, 3973, 2932, 4087],
 [646,
  672,
  51,
  3140,
  1344,
  51,
  2397,
  3188,
  3973,
  389,
  1531,
  3249,
  1330,
  4695,
  4851,
  4659,
  1572,
  3822,
  1,
  558,
  2100,
  4150,
  3358,
  4289,
  4395,
  1341,
  1211,
  4672,
  631,
  3585,
  4087],
 [4087,
  646,
  987,
  3482,
  51,
  3973,
  3282,
  558,
  3196,
  2881,
  3822,
  290,
  195,
  547,
  4150,
  508,
  4157,
  3674,
  298,
  2199,
  40,
  4511],
 [4810,
  672,
  2100,
  2192,
  4526,
  730,
  1508,
  2960,
  1269,
  3482,
  4798,
  2395,
  2199,
  40,
  4511],
 [1278, 1679, 1289, 1228, 301, 2199, 40, 4511, 2944],
 [3267,
  987,
  3482,
  2100,
  2192,
  428,
  1158,
  193,
  4659,
  2351,
  3312,
  2199,
  40,
  4511],
 [2100,
  1743,
  4156,
  2630,
  690,
  2660,
  3726,
  3972,
  3822,
  290,
  3687,
  2960,
  3913,
  195,
  167,
  3230,
  3822,
  1330,
  538,
  2960,
  1238,
  

Embedding representation

In [152]:
len(embedded_docs)

2824

In [153]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...  926  508 1266]
 [   0    0    0 ... 2199   40 4511]
 [   0    0    0 ... 3973 2932 4087]
 ...
 [   0    0    0 ... 4723 3240 3545]
 [   0    0    0 ... 3345 4750 4240]
 [   0    0    0 ...  631 2197 2601]]


In [154]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0, 4069,  783, 2397,
       4672,  124,  713, 2098, 1072, 3913,  926,  508, 1266], dtype=int32)

In [155]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(13,activation='softmax'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_7 (Embedding)     (None, 20, 40)            200000    
                                                                 
 lstm_7 (LSTM)               (None, 100)               56400     
                                                                 
 dense_7 (Dense)             (None, 13)                1313      
                                                                 
Total params: 257,713
Trainable params: 257,713
Non-trainable params: 0
_________________________________________________________________
None


In [101]:
len(embedded_docs)

2824

In [156]:
# y=reddit_data['flair']
# # y.unique()
Y.shape

(2824, 13)

In [157]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(Y)

In [158]:
X_final.shape,y_final.shape

((2824, 20), (2824, 13))

In [106]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.2, random_state=42)

In [107]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=50,batch_size=64)

Epoch 1/50
36/36 [==============================] - 4s 50ms/step - loss: 0.4214 - accuracy: 0.0717 - val_loss: 0.2658 - val_accuracy: 0.0743
Epoch 2/50
36/36 [==============================] - 1s 35ms/step - loss: 0.2658 - accuracy: 0.0903 - val_loss: 0.2638 - val_accuracy: 0.0832
Epoch 3/50
36/36 [==============================] - 1s 34ms/step - loss: 0.2631 - accuracy: 0.1040 - val_loss: 0.2608 - val_accuracy: 0.1504
Epoch 4/50
36/36 [==============================] - 1s 35ms/step - loss: 0.2583 - accuracy: 0.2205 - val_loss: 0.2546 - val_accuracy: 0.2142
Epoch 5/50
36/36 [==============================] - 1s 35ms/step - loss: 0.2499 - accuracy: 0.2452 - val_loss: 0.2468 - val_accuracy: 0.2195
Epoch 6/50
36/36 [==============================] - 1s 35ms/step - loss: 0.2404 - accuracy: 0.2532 - val_loss: 0.2384 - val_accuracy: 0.2283
Epoch 7/50
36/36 [==============================] - 1s 34ms/step - loss: 0.2318 - accuracy: 0.3311 - val_loss: 0.2329 - val_accuracy: 0.2195
Epoch 8/50
36

In [109]:
acc=model.evaluate(X_test,y_test)

18/18 [==============================] - 0s 7ms/step - loss: 0.3516 - accuracy: 0.3699


In [114]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(60))
model.add(Dropout(0.3))
model.add(Dense(13,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [118]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=50,batch_size=64)

Epoch 1/50
36/36 [==============================] - 1s 25ms/step - loss: 0.1695 - accuracy: 0.5449 - val_loss: 0.2186 - val_accuracy: 0.3451
Epoch 2/50
36/36 [==============================] - 1s 24ms/step - loss: 0.1637 - accuracy: 0.5750 - val_loss: 0.2188 - val_accuracy: 0.3221
Epoch 3/50
36/36 [==============================] - 1s 24ms/step - loss: 0.1575 - accuracy: 0.6118 - val_loss: 0.2188 - val_accuracy: 0.3646
Epoch 4/50
36/36 [==============================] - 1s 24ms/step - loss: 0.1502 - accuracy: 0.6344 - val_loss: 0.2169 - val_accuracy: 0.3628
Epoch 5/50
36/36 [==============================] - 1s 24ms/step - loss: 0.1437 - accuracy: 0.6737 - val_loss: 0.2196 - val_accuracy: 0.3628
Epoch 6/50
36/36 [==============================] - 1s 25ms/step - loss: 0.1363 - accuracy: 0.7034 - val_loss: 0.2208 - val_accuracy: 0.3699
Epoch 7/50
36/36 [==============================] - 1s 24ms/step - loss: 0.1304 - accuracy: 0.7357 - val_loss: 0.2210 - val_accuracy: 0.3664
Epoch 8/50
36

In [119]:
acc=model.evaluate(X_test,y_test)

18/18 [==============================] - 0s 6ms/step - loss: 0.3629 - accuracy: 0.3894


In [159]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
MAX_NB_WORDS = 50000
# Max number of words in each complaint.
MAX_SEQUENCE_LENGTH = 250
# This is fixed.
EMBEDDING_DIM = 100
tokenizer = Tokenizer(num_words=MAX_NB_WORDS, filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~', lower=True)
tokenizer.fit_on_texts(df['title'].values)
word_index = tokenizer.word_index
print('Found %s unique tokens.' % len(word_index))

Found 8312 unique tokens.


In [160]:
X = tokenizer.texts_to_sequences(df['title'].values)
X = pad_sequences(X, maxlen=MAX_SEQUENCE_LENGTH)
print('Shape of data tensor:', X.shape)

Shape of data tensor: (2824, 250)


In [161]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.10, random_state = 42)
print(X_train.shape,Y_train.shape)
print(X_test.shape,Y_test.shape)

(2541, 250) (2541, 13)
(283, 250) (283, 13)


In [162]:
from keras.models import Sequential
from keras.layers import Dense, Embedding, LSTM, SpatialDropout1D
from sklearn.model_selection import train_test_split
from keras.utils.np_utils import to_categorical
from keras.callbacks import EarlyStopping
from keras.layers import Dropout

In [170]:
model = Sequential()
model.add(Embedding(MAX_NB_WORDS, EMBEDDING_DIM, input_length=X.shape[1]))
model.add(SpatialDropout1D(0.2))
model.add(LSTM(100, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(13, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_9 (Embedding)     (None, 250, 100)          5000000   
                                                                 
 spatial_dropout1d_1 (Spatia  (None, 250, 100)         0         
 lDropout1D)                                                     
                                                                 
 lstm_9 (LSTM)               (None, 100)               80400     
                                                                 
 dense_9 (Dense)             (None, 13)                1313      
                                                                 
Total params: 5,081,713
Trainable params: 5,081,713
Non-trainable params: 0
_________________________________________________________________
None


In [171]:
### Finally Training
model.fit(X_train,Y_train,validation_data=(X_test,Y_test),epochs=8,batch_size=64)

Epoch 1/8
40/40 [==============================] - 34s 780ms/step - loss: 2.4869 - accuracy: 0.1614 - val_loss: 2.3888 - val_accuracy: 0.2049
Epoch 2/8
40/40 [==============================] - 31s 777ms/step - loss: 2.2006 - accuracy: 0.2464 - val_loss: 2.0962 - val_accuracy: 0.2544
Epoch 3/8
40/40 [==============================] - 31s 772ms/step - loss: 1.8442 - accuracy: 0.4128 - val_loss: 1.8523 - val_accuracy: 0.3710
Epoch 4/8
40/40 [==============================] - 31s 775ms/step - loss: 1.3584 - accuracy: 0.5789 - val_loss: 1.7038 - val_accuracy: 0.4382
Epoch 5/8
40/40 [==============================] - 31s 772ms/step - loss: 0.9172 - accuracy: 0.7375 - val_loss: 1.6911 - val_accuracy: 0.4452
Epoch 6/8
40/40 [==============================] - 31s 778ms/step - loss: 0.5886 - accuracy: 0.8512 - val_loss: 1.7634 - val_accuracy: 0.4700
Epoch 7/8
40/40 [==============================] - 31s 775ms/step - loss: 0.3829 - accuracy: 0.9091 - val_loss: 1.8189 - val_accuracy: 0.4841
Epoch 

In [172]:
accr = model.evaluate(X_test,Y_test)
print('Test set\n  Loss: {:0.3f}\n  Accuracy: {:0.3f}'.format(accr[0],accr[1]))

9/9 [==============================] - 1s 71ms/step - loss: 1.9933 - accuracy: 0.4523
Test set
  Loss: 1.993
  Accuracy: 0.452
